<p class="contenedor">ERROR EN LA BASE DE DATOS: NO PUEDES ELIMINAR UN VENDEDOR QUE ESTA ASIGNADO A UNA PROPIEDAD</p>
<p class="contenedor">ACTUALIZA EL VENDEDOR DE LA PROPIEDAD O ELIMINA LA PROPIEDAD PARA DESPUES PODER ELIMINAR EL VENDEDOR</p>
<p style="display: none;"><?php echo $mensaje; ?></p>